app/models.py
from app import db

class User(db.Model):
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String)

    def __repr__(self):
        return f'User: {self.username}'

    def commit(self):
        db.session.add(self)
        db.session.commit()

        

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo


class RegisterForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired()])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

# Followed along Corey Shafer's tutorial in addition to lecture notes

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
Migrate = Migrate(app, db)

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)
from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)

from app import models

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from . import bp as app
from flask import render_template
from app.resources.countries import Country
import random

@app.route('/')
def home():
    return render_template('index.jinja')

@app.route('/about')
def about():
    return render_template('about.jinja', title='About')

@app.route('/buzz')
def buzz():
    def random_ten_countries():
        random.shuffle(Country)
        country_list = Country[:10]
        return country_list
    return render_template('buzz.jinja', title='Trending', countries=random_ten_countries())

app/templates/about.jinja
{% extends 'base.jinja' %}

{% block content %}

<h3>About page</h3>
<p>Look no further for the all-in-one website to hang out with your friends. Play games, have a karaoke session, video chat and more! </p>

{% endblock %}

app/templates/base.jinja
<!doctype html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title>Playhouse</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Playhouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.buzz') }}">What's
                                Trending</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.signin') }}">Sign
                                In</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages%}
        <li> {{ message }} </li>
        {% endfor%}
    </ul>
    {% endif %}
    {% endwith %}


    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/buzz.jinja
{% extends 'base.jinja' %}

{% block content %}

<h1>Trending by country</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">RANKING</th>
            <th scope="col">COUNTRY</th>
        </tr>
    </thead>
    <tbody>
        {% for i in range(10) %}
        <tr>
            <th scope="row">{{ i }}</th>
            <td> {{ countries[i][1] }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/index.jinja
{% extends 'base.jinja' %}

{% block content %}

<h2>Welcome to Playhouse</h2>
<h3>Hang out with your friends wherever you are!</h3>

{% endblock %}

app/templates/register.jinja
{% extends 'base.jinja' %}

{% block content %}

{{ form.hidden_tag()}}
<div>
    <form action="" method="POST">
        <fieldset class="form_group">
            <legend>Register Here</legend>
            <div>
                {{ form.username.label }} <br>
                {{ form.username(size=32) }}
            </div>
            <div>
                {{ form.email.label }} <br>
                {{ form.email(size=32) }}
                {% for error in form.email.errors%}
                <span> {{ error }}</span>
                {% endfor %}
            </div>
            <div>
                {{ form.password.label }} <br>
                {{ form.password(size=32) }}
            </div>
        </fieldset>
        <div>
            {{ form.submit }}
        </div>
    </form>
    <div>
        <p> Already have an account?
        </p>
        <a href="{{ url_for('auth.signin') }}">Sign In Here</a>
    </div>
</div>

{% endblock content %}

app/templates/signin.jinja
{% extends 'base.jinja' %}

{% block content %}

{{ form.hidden_tag()}}
<div>
    <form action="">
        <fieldset class="form_group">
            <legend>Sign In Here</legend>
            <div>
                {{ form.email.label }} <br>
                {{ form.email(size=32) }}
                {% for error in form.email.errors%}
                <span> {{ error }}</span>
                {% endfor %}
            </div>
            <div>
                {{ form.password.label }} <br>
                {{ form.password(size=32) }}
            </div>
        </fieldset>
        <div>
        <br>
            {{ form.submit }}
        </div>
    </form>
    <div>
        <p> Need to register?
        </p>
        <a href="{{ url_for('auth.register') }}">Register Here</a>
    </div>
</div>

{% endblock content %}